services:
  # 自动初始化前端 dist 到 named volume
  # dist-init:
  #   # image: jsherp-app:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   # command: ["/bin/sh", "-c", "cp -r /app/* /project/"]
  #   volumes:
  #     - ./released:/app
  #   restart: "no"

  # 后端服务
  erp-backend:
    # image: openjdk:8-jre-slim
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erp-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://$MYSQL_SERVER:$MYSQL_SERVER_PORT/jsh_erp?useUnicode=true&characterEncoding=utf8&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: jsh_erp
      SPRING_DATASOURCE_PASSWORD: $MYSQL_USER_PASSWORD
      SPRING_REDIS_HOST: $REDIS_HOST
      SPRING_REDIS_PASSWORD: $REDIS_PASSWORD
      MYSQL_SERVER_PORT: $MYSQL_SERVER_PORT
    depends_on:
      # - dist-init
      - mysql
      - redis
    # ports:
    #   - "9999:9999"
    restart: unless-stopped
    volumes:
      - ./released:/app
    command: ["/bin/sh", "-c", "cd /app/backend && ./bin/start.sh"]
    networks:
      - web_net
    logging:
      driver: "json-file"
      options:
        # 单个文件最大 10MB
        max-size: "10m"
        # 最多保留 3 个文件（当前 + 2 个轮转文件）
        max-file: "3"

  # Nginx 静态资源服务
  erp-nginx:
    image: nginx:1.21.5
    container_name: erp-nginx
    volumes:
      - ./released/frontend/dist:/home/jshERP/jshERP-web
      - ./released/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "11300:3000"
    depends_on:
      - erp-backend
    restart: unless-stopped
    networks:
      - web_net

  # Redis
  erp-redis:
    image: redis:7-alpine
    container_name: erp-redis
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    # ports:
    #   - "6379:6379"
    restart: unless-stopped
    # depends_on:
      # - dist-init
    networks:
      - web_net

  # MySQL
  erp-mysql:
    image: mysql:5.7
    container_name: erp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jsh_erp
      MYSQL_USER: jsh_erp
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    # ports:
    #   - "3306:3306"
    volumes:
      - ./released/utf8mb4.cnf:/etc/mysql/conf.d/utf8mb4.cnf
      - ./released/backend/docs/jsh_erp.sql:/docker-entrypoint-initdb.d/jsh_erp.sql
      - ./released/mysqldata:/var/lib/mysql
    restart: unless-stopped
    # depends_on:
      # - dist-init
    networks:
      - web_net

networks:
  web_net:
    external: true